### ISSUE TITLE
locking from two consecutive jvms cause latter one not getting lock(correct) and hangs(incorrect?)

### ISSUE THREAD

**Issue by alfonz19** [sanyarnd/applocker#3]
Based on api design I'd expect, that locking should be non-blocking, yet it is kinda "blocking".

call chain:
io.github.sanyarnd.applocker.AppLocker#lock --> lockInternal --> gLock.loopLock() --> io.github.sanyarnd.applocker.Lock#lock

this will throw `OverlappingFileLockException` in case the lock is already held, but in LoopLock:

```
while (true) {
            try {
                lock();
                // if lock is succeeded -- return
                return;
            } catch (LockingBusyException ignored) {
            }
            // we dont catch LockingFailedException, propagate it up to the stack
        }
```

we swallow it making the call "blocking". The apostrophes are here, since once the lock is released, I'm getting onFail callback (instead of onBusy). So it's not non-blocking, and it's not blocking either, because after lock release there is incorrect handling of situation. If anything, lock should be acquired after released and code should continue. But really, I think it should be non-blocking, call onBusy and that's it.

linux, openjdk version "11.0.9.1" 2020-11-04

**Comment by sanyarnd** [comment]
I need to read the code again, but what I remember:
* there are two locks: global and application
* global lock ensures noone is writing in the same directory, making access to the dir exclusive, this is required because app lock writes to multiple files, and writing to multiple files is non-atomic operation
* app lock works on application level, ensures noone is modifying the lock in the same app from different threads

There is a spin-lock on global lock, because as far as I understand, locking operations are fast. There shouldn't be any processing inside handlers (like in any pub/sub system). 

I'll look at the code this evening and validate the logic.

We can add non-blocking version in API too (like lock/tryLock in ReentrantLock), but it's up to the user how to process such situation.

**Comment by alfonz19** [comment]
what is the resolution? Wont-fix as there is no new version?

**Comment by sanyarnd** [comment]
Sorry, forgot to specify PR: #4
